name: ci
on: push
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install dependencies 📦
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Check types 🧾
        run: npm run types

      - name: Catch it.only 🫴
        run: npm run stop-only

      - name: Run tests 🧪
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm start

  test-merge-coverage:
    runs-on: ubuntu-20.04
    env:
      DEBUG: code-coverage
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install dependencies 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Merge coverage tests
        working-directory: examples/merge-coverage
        run: |
          npm run cy:run1
          npm run cy:run2
          npm run merge

  release:
    needs: [test, test-merge-coverage]
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install only the semantic release 📦
        run: npm install semantic-release

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
